# Generated by Django 5.1.6 on 2025-04-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=200)),
                ('Referencia', models.CharField(max_length=30)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('Ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
