# Generated by Django 5.1.6 on 2025-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_categoria_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(related_name='produtos', to='produtos.categoria'),
        ),
        migrations.DeleteModel(
            name='Produto_Categoria',
        ),
    ]
